spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    show-sql: true

  mvc:    pathmatch:      matching-strategy: ant-path-matcher
    